"""cria tabela enderecos

Revision ID: 992a7522d110
Revises:
Create Date: 2026-09-17 11:53:31.285769

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "992a7522d110"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enderecos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cep", sa.CHAR(length=8), nullable=False),
        sa.Column(
            "logradouro", sa.String(length=255), server_default="", nullable=False
        ),
        sa.Column(
            "complemento", sa.String(length=255), server_default="", nullable=False
        ),
        sa.Column("bairro", sa.String(length=120), server_default="", nullable=False),
        sa.Column("localidade", sa.String(length=120), nullable=False),
        sa.Column("uf", sa.CHAR(length=2), nullable=False),
        sa.Column("ibge", sa.String(length=7), server_default="", nullable=False),
        sa.Column("ddd", sa.String(length=2), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cep ~ '^[0-9]{8}$'", name=op.f("ck_enderecos_cep_formato")),
        sa.CheckConstraint("uf ~ '^[A-Z]{2}$'", name=op.f("ck_enderecos_uf_formato")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enderecos")),
        sa.UniqueConstraint("cep", name=op.f("uq_enderecos_cep")),
    )
    op.create_index(
        op.f("ix_enderecos_uf_localidade"),
        "enderecos",
        ["uf", "localidade"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enderecos_uf_localidade"), table_name="enderecos")
    op.drop_table("enderecos")
    # ### end Alembic commands ###
